- name: Download remove.sh
  ansible.builtin.get_url:
    url: "{{ run_remove_url }}"
    dest: hello-world/
    mode: '0755'
  when: run_remove == 'remove.sh'

- name: Removing Skupper sites
  ansible.builtin.command:
    argv:
      - "hello-world/{{ run_remove }}"
      - "{{ item }}"
  loop:
    - "east"
    - "west"
  retries: 3
  delay: 5
  register: _remove
  changed_when: not _remove.failed
