---
collections:
  - name: ansible.posix
    version: 1.4.0

  - name: ansible.scm
    version: 2.0.0

  - name: ansible.utils
    version: 4.0.0

  - name: community.docker

  - name: containers.podman
    version: 1.15.4
