---
- name: Run rootful smoke tests
  hosts: rootful
  tasks:
    - name: Run rootful smoke tests
      ansible.builtin.include_role:
        name: fgiorgetti.nonkube_smoke_tests.run
      vars:
        run_command: "{{ item.command }}"
        run_platform: "{{ item.platform }}"
      loop: "{{ matrix }}"
    - name: Cleanup rootful smoke tests
      ansible.builtin.include_role:
        name: fgiorgetti.nonkube_smoke_tests.cleanup
      tags: [ always ]
