---
- name: Cleanup nonkube smoke test as non-root
  hosts: rootless
  tasks:
    - name: Cleanup rootless smoke tests
      ansible.builtin.include_role:
        name: fgiorgetti.nonkube_smoke_tests.cleanup
      vars:
        run_remove: "{{ item.remove }}"
      tags: [always]

- name: Cleanup rootful smoke tests
  hosts: rootful
  tasks:
    - name: Cleanup rootful smoke tests
      ansible.builtin.include_role:
        name: fgiorgetti.nonkube_smoke_tests.cleanup
      vars:
        run_remove: "{{ item.remove }}"
      tags: [always]
