---
all:
  hosts:
    ci:
      ansible_connection: local
    ci-root:
      ansible_connection: local
      ansible_become: true
  children:
    rootful:
      hosts:
        ci-root:
    rootless:
      hosts:
        ci:
