---
all:
  hosts:
    fedora39:
      ansible_host: 192.168.124.1
    fedora39-root:
      ansible_host: 192.168.124.1
    rhel9:
      ansible_host: 10.0.134.3
    rhel9-root:
      ansible_host: 10.0.134.3
    ubuntu:
      ansible_host: 192.168.124.179
    ubuntu-root:
      ansible_host: 192.168.124.179
    ci:
      ansible_connection: local
    ci-root:
      ansible_connection: local
  children:
    rootful:
      hosts:
        fedora39-root:
        rhel9-root:
        ubuntu-root:
        ci-root:
    rootless:
      hosts:
        fedora39:
        rhel9:
        ubuntu:
        ci:
