---
matrix:
  - { command: ["skupper", "system", "start"], remove: ["skupper", "system", "stop", "-n"], platform: "docker" }
ce_commands:
  # https://docs.docker.com/engine/security/rootless/
  - dockerd-rootless-setuptool.sh  install --force
#  - systemctl --user enable --now docker.socket
DOCKER_HOST: "unix://{{ ansible_env.XDG_RUNTIME_DIR }}/docker.sock"

