---
run_cli_url: https://github.com/skupperproject/skupper/releases/download/2.2.0/skupper-cli-2.2.0-linux-amd64.tgz
run_bootstrap_url: https://raw.githubusercontent.com/skupperproject/skupper/refs/heads/2.2/cmd/bootstrap/bootstrap.sh
