---
run_cli_url: https://github.com/skupperproject/skupper/releases/download/v2-dev-release/skupper-cli-v2-dev-release-linux-amd64.tgz
run_bootstrap_url: https://github.com/skupperproject/skupper/raw/refs/heads/2.0/cmd/bootstrap/bootstrap.sh
