apiVersion: skupper.io/v2alpha1
kind: RouterAccess
metadata:
  name: go-west
  namespace: west
spec:
  roles:
    - port: 55671
      name: inter-router
    - port: 45671
      name: edge
  bindHost: 127.0.0.1
