---
all:
  children:
    rootful:
      children:
        rootful_docker:
        rootful_podman:
        rootful_linux:
    rootless:
      children:
        rootless_docker:
        rootless_podman:
        rootless_linux:
