---
matrix:
  - { command: ["./skupper", "system", "setup"], remove: ["./skupper", "system", "teardown", "-n"], platform: "podman" }
  - { command: ["./skupper", "system", "setup"], remove: ["./skupper", "system", "teardown", "-n"], platform: "docker" }
  - { command: ["./skupper", "system", "setup"], remove: ["./skupper", "system", "teardown", "-n"], platform: "systemd" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "podman" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "docker" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "systemd" }
