---
matrix:
  - { command: "bootstrap", platform: "podman" }
  - { command: "bootstrap", platform: "docker" }
  - { command: "bootstrap", platform: "systemd" }
  - { command: "bootstrap.sh", platform: "podman" }
  - { command: "bootstrap.sh", platform: "docker" }
  - { command: "bootstrap.sh", platform: "systemd" }
