---
ansible_user: root
link_path: /usr/local/share/skupper/namespaces/west/runtime/link
ce_commands:
  - systemctl enable --now docker.socket
#  - systemctl enable --now podman.socket
matrix:
  - { command: "bootstrap", platform: "docker" }
  - { command: "bootstrap", platform: "systemd" }
  - { command: "bootstrap.sh", platform: "docker" }
  - { command: "bootstrap.sh", platform: "systemd" }
