---
ansible_user: root
skupper_home: /var/lib/skupper
ce_commands:
  - systemctl enable --now docker.socket
#  - systemctl enable --now podman.socket
matrix:
  - { command: ["./skupper", "system", "setup"], remove: ["./skupper", "system", "teardown", "-n"], platform: "docker" }
  - { command: ["./skupper", "system", "setup"], remove: ["./skupper", "system", "teardown", "-n"], platform: "linux" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "docker" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "linux" }
