---
ansible_user: runner
skupper_home: /home/runner/.local/share/skupper
ce_commands:
  - systemctl --user enable --now podman.socket
matrix:
  - { command: ["./skupper", "system", "start"], remove: ["./skupper", "system", "stop", "-n"], platform: "podman" }
  - { command: ["./skupper", "system", "start"], remove: ["./skupper", "system", "stop", "-n"], platform: "docker" }
  - { command: ["./skupper", "system", "start"], remove: ["./skupper", "system", "stop", "-n"], platform: "linux" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "podman" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "docker" }
  - { command: ["./bootstrap.sh"], remove: ["./remove.sh"], platform: "linux" }
