---
name: "CI"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-24.04
    steps:
      - uses: ansible/ansible-lint@main
        name: Run ansible-lint
        with:
          requirements_file: "./.github/scripts/requirements.yml"

  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint@main
        name: Run ansible-lint
      - name: Builds and installs the skupper-router
        uses: ./.github/actions/build-router
      - name: Builds and installs the bootstrap code
        uses: ./.github/actions/build-bootstrap
      - name: Runs the Smoke Tests
        uses: ./.github/actions/run-smoke-test
