---
name: "CI"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-24.04
    steps:
      - uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
        with:
          path: "collections/ansible_collections/fgiorgetti"
      - uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
        with:
          path: "./*.yaml"
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Builds and installs the skupper-router
        uses: ./.github/actions/build-router
      - name: Runs the Smoke Tests
        uses: ./.github/actions/run-smoke-test
